perk_order = {
    "CRITICAL_HIT",
    "BREATH_UNDERWATER",
    "EXTRA_MONEY",
    "EXTRA_MONEY_TRICK_KILL",
    "GOLD_IS_FOREVER",
    "TRICK_BLOOD_MONEY",
    "EXPLODING_GOLD",
    "HOVER_BOOST",

    "HASTE", --Modded
    "LOW_GRAVITY", --Modded
    "HIGH_GRAVITY", --Modded

    "STRONG_KICK",
    "TELEKINESIS",
    "REPELLING_CAPE",
    "EXPLODING_CORPSES",
    "SAVING_GRACE",
    "GLOBAL_GORE",
    "REMOVE_FOG_OF_WAR",
    "LEVITATION_TRAIL",
    "VAMPIRISM",

    "HEART_STEALER", --Modded

    "EXTRA_HP",
    "HEARTS_MORE_EXTRA_HP",
    "GLASS_CANNON",
    "LOW_HP_DAMAGE_BOOST",
    "RESPAWN",
    "WORM_ATTRACTOR",
    "RADAR_ENEMY",
    "FOOD_CLOCK",
    "IRON_STOMACH",
    "WAND_RADAR",
    "ITEM_RADAR",
    "MOON_RADAR",
    "MAP",

    "MAP_LEVEL_2", --Modded
    "MAP_LEVEL_3", --Modded
    "MAP_LEVEL_4", --Modded

    "PROTECTION_FIRE",
    "PROTECTION_RADIOACTIVITY",
    "PROTECTION_EXPLOSION",
    "PROTECTION_MELEE",
    "PROTECTION_ELECTRICITY",

    "PROTECTION_FREEZE", --Modded

    "TELEPORTITIS",
    "TELEPORTITIS_DODGE",
    "STAINLESS_ARMOUR",
    "EDIT_WANDS_EVERYWHERE",
    "NO_WAND_EDITING",
    "WAND_EXPERIMENTER",
    "ADVENTURER",
    "ABILITY_ACTIONS_MATERIALIZED",
    "PROJECTILE_HOMING",
    "PROJECTILE_HOMING_SHOOTER",
    "UNLIMITED_SPELLS",
    "FREEZE_FIELD",
    "FIRE_GAS",
    "DISSOLVE_POWDERS",
    "BLEED_SLIME",
    "BLEED_OIL",
    "BLEED_GAS",

    "CRYO_BLOOD", --Modded

    "SHIELD",
    "REVENGE_EXPLOSION",
    "REVENGE_TENTACLE",
    "REVENGE_RATS",
    "REVENGE_BULLET",
    "ATTACK_FOOT",
    "LEGGY_FEET",
    "PLAGUE_RATS",
    "VOMIT_RATS",
    "CORDYCEPS",
    "MOLD",
    "WORM_SMALLER_HOLES",
    "PROJECTILE_REPULSION",
    "RISKY_CRITICAL",
    "FUNGAL_DISEASE",
    "PROJECTILE_SLOW_FIELD",
    "PROJECTILE_REPULSION_SECTOR",
    "PROJECTILE_EATER_SECTOR",
    "ORBIT",
    "ANGRY_GHOST",
    "HUNGRY_GHOST",
    "DEATH_GHOST",
    "HOMUNCULUS",
    "LUKKI_MINION",
    "ELECTRICITY",
    "ATTRACT_ITEMS",
    "EXTRA_KNOCKBACK",
    "LOWER_SPREAD",
    "LOW_RECOIL",
    "BOUNCE",
    "FAST_PROJECTILES",
    "ALWAYS_CAST",
    "EXTRA_MANA",
    "NO_MORE_SHUFFLE",
    "NO_MORE_KNOCKBACK",
    "DUPLICATE_PROJECTILE",
    "FASTER_WANDS",
    "EXTRA_SLOTS",
    "CONTACT_DAMAGE",
    "EXTRA_PERK",
    "PERKS_LOTTERY",
    "GAMBLE",

    "ROLL_AGAIN", --Modded

    "EXTRA_SHOP_ITEM",

    "EXTRA_POTION_AND_SACK_CAPACITY", --Modded

    "GENOME_MORE_HATRED",
    "GENOME_MORE_LOVE",
    "PEACE_WITH_GODS",
    "MANA_FROM_KILLS",
    "ANGRY_LEVITATION",
    "LASER_AIM",
    "MEGA_BEAM_STONE"
}
